
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';
export const LOGOUT_USER= 'LOGOUT_USER';
export const GET_USER_LIST = 'GET_USER_LIST';

export const GET_BOOK_LIST = 'GET_BOOK_LIST';